# Generated by Django 4.2 on 2023-07-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_weatherstation_description_weatherstation_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MushroomSpot',
        ),
    ]
