# Generated by Django 4.2 on 2023-05-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0004_multiarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiarea',
            old_name='line',
            new_name='areas',
        ),
    ]
