# Generated by Django 4.2 on 2023-10-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0005_rename_line_multiarea_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='markers/'),
        ),
    ]
