# Generated by Django 4.2 on 2023-10-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0006_marker_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='picture',
            new_name='image',
        ),
    ]
