# Generated by Django 4.2 on 2023-10-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0007_rename_picture_marker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='beschrijving',
            field=models.TextField(blank=True, help_text='Beschrijving van de area', verbose_name='Area beschrijving'),
        ),
    ]
