# Generated by Django 4.2 on 2023-10-10 12:28

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0008_area_beschrijving'),
    ]

    operations = [
        migrations.CreateModel(
            name='areaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('type', models.CharField(max_length=100, verbose_name='Area Type')),
                ('beschrijving', models.TextField(blank=True, verbose_name='Beschrijving')),
            ],
            options={
                'verbose_name': 'area-type',
                'verbose_name_plural': 'area types',
                'ordering': ['type'],
            },
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name'], 'verbose_name': 'area', 'verbose_name_plural': 'areas'},
        ),
        migrations.AddField(
            model_name='area',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='markers.areatype'),
        ),
    ]
